name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ darwin.o2switch.net.SERVER }}
          username: ${{ jafo7150.FTP_USERNAME }}
          password: ${{ R8Wt-NxKU-Lxm(.FTP_PASSWORD }}
          server-dir: v-vander.fr/
          local-dir: dist/
