name: Deploy to 02switch via FTP

on:
  push:
    branches:
      - main  # Cette configuration déclenche le déploiement lorsqu'un commit est poussé sur la branche `main`.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer la dernière version stable de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'  # Utilise la dernière version stable LTS de Node.js

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          npm install

      # Étape 4 : Construire le projet pour la production
      - name: Build project
        run: |
          npm run build

      # Étape 5 : Déployer sur le serveur FTP de 02switch
      - name: Deploy to 02switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ftp://ftp.v-vander.fr  # Remplace par l'URL de ton serveur FTP
          ftp-username: ${{ secrets.FTP_USERNAME }}  # Secret contenant ton nom d'utilisateur FTP
          ftp-password: ${{ secrets.FTP_PASSWORD }}  # Secret contenant ton mot de passe FTP
          local-dir: ./dist  # Le répertoire contenant les fichiers générés après `npm run build`
          remote-dir: /public_html  # Le répertoire cible sur ton serveur 02switch (par défaut, c'est souvent `public_html`)
